/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as dashboardDashboardImport } from './routes/(dashboard)/dashboard'
import { Route as dashboardContactImport } from './routes/(dashboard)/contact'
import { Route as dashboardBillingImport } from './routes/(dashboard)/billing'
import { Route as dashboardAutomationImport } from './routes/(dashboard)/automation'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardDashboardRoute = dashboardDashboardImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const dashboardContactRoute = dashboardContactImport.update({
  id: '/(dashboard)/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const dashboardBillingRoute = dashboardBillingImport.update({
  id: '/(dashboard)/billing',
  path: '/billing',
  getParentRoute: () => rootRoute,
} as any)

const dashboardAutomationRoute = dashboardAutomationImport.update({
  id: '/(dashboard)/automation',
  path: '/automation',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/automation': {
      id: '/(dashboard)/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof dashboardAutomationImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/billing': {
      id: '/(dashboard)/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof dashboardBillingImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/contact': {
      id: '/(dashboard)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof dashboardContactImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof dashboardAutomationRoute
  '/billing': typeof dashboardBillingRoute
  '/contact': typeof dashboardContactRoute
  '/dashboard': typeof dashboardDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof dashboardAutomationRoute
  '/billing': typeof dashboardBillingRoute
  '/contact': typeof dashboardContactRoute
  '/dashboard': typeof dashboardDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(dashboard)/automation': typeof dashboardAutomationRoute
  '/(dashboard)/billing': typeof dashboardBillingRoute
  '/(dashboard)/contact': typeof dashboardContactRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/automation' | '/billing' | '/contact' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/automation' | '/billing' | '/contact' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/automation'
    | '/(dashboard)/billing'
    | '/(dashboard)/contact'
    | '/(dashboard)/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardAutomationRoute: typeof dashboardAutomationRoute
  dashboardBillingRoute: typeof dashboardBillingRoute
  dashboardContactRoute: typeof dashboardContactRoute
  dashboardDashboardRoute: typeof dashboardDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardAutomationRoute: dashboardAutomationRoute,
  dashboardBillingRoute: dashboardBillingRoute,
  dashboardContactRoute: dashboardContactRoute,
  dashboardDashboardRoute: dashboardDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(dashboard)/automation",
        "/(dashboard)/billing",
        "/(dashboard)/contact",
        "/(dashboard)/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(dashboard)/automation": {
      "filePath": "(dashboard)/automation.tsx"
    },
    "/(dashboard)/billing": {
      "filePath": "(dashboard)/billing.tsx"
    },
    "/(dashboard)/contact": {
      "filePath": "(dashboard)/contact.tsx"
    },
    "/(dashboard)/dashboard": {
      "filePath": "(dashboard)/dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
